# Notebook 01 - Data Collection

### Objetivo
Centralizar la adquisición de datos y documentar su origen, formato y versión.

### Fuentes de datos

Archivos locales .csv
- `contract.csv` — información del contrato;
- `personal.csv` — datos personales del cliente;
- `internet.csv` — información sobre los servicios de Internet;
- `phone.csv` — información sobre los servicios telefónicos.

### Notas
- La información se toma con fecha del 1 de febrero de 2020.
En cada archivo, la columna `customerID` (ID de cliente) contiene un código único asignado a cada cliente.

In [1]:
## Inicialización
import pandas as pd

In [2]:
## Cargar datos
raw_path = '../data/raw/' # Directorio donde se ubican los archivos
df_contract = pd.read_csv(raw_path+'contract.csv')
df_personal = pd.read_csv(raw_path+'personal.csv')
df_internet = pd.read_csv(raw_path+'internet.csv')
df_phone = pd.read_csv(raw_path+'phone.csv')

### Archivo 1 (contract.csv)

In [3]:
# Resumen inicial
df_contract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   object
 2   EndDate           7043 non-null   object
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
dtypes: float64(1), object(7)
memory usage: 440.3+ KB

In [4]:
# Inspección de algunos elementos para comprobar que la estructura es coherente
df_contract.head(3)

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15

### Archivo 2 (personal.csv)

In [5]:
# Resumen inicial
df_personal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [6]:
# Inspección de algunos elementos para tener mayor familaridad
df_personal.head(3)

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No

### Archivo 3 (internet.csv)

In [7]:
# Resumen inicial
df_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5517 non-null   object
 1   InternetService   5517 non-null   object
 2   OnlineSecurity    5517 non-null   object
 3   OnlineBackup      5517 non-null   object
 4   DeviceProtection  5517 non-null   object
 5   TechSupport       5517 non-null   object
 6   StreamingTV       5517 non-null   object
 7   StreamingMovies   5517 non-null   object
dtypes: object(8)
memory usage: 344.9+ KB

In [8]:
# Inspección de algunos elementos para tener mayor familaridad
df_internet.head(3)

,customerID,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,DSL,Yes,Yes,No,No,No,No

### Archivo 4 (phone.csv)

In [9]:
# Resumen inicial
df_phone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6361 entries, 0 to 6360
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     6361 non-null   object
 1   MultipleLines  6361 non-null   object
dtypes: object(2)
memory usage: 99.5+ KB

In [10]:
# Inspección de algunos elementos para tener mayor familaridad
df_phone.head()

   customerID MultipleLines
0  5575-GNVDE            No
1  3668-QPYBK            No
2  9237-HQITU            No
3  9305-CDSKC           Yes
4  1452-KIOVK           Yes

### Guardar datos

In [11]:
df_contract.to_csv(raw_path+'contract_raw.csv', index=False)
df_personal.to_csv(raw_path+'personal_raw.csv', index=False)
df_internet.to_csv(raw_path+'internet_raw.csv', index=False)
df_phone.to_csv(raw_path+'phone_raw.csv', index=False)