# Notebook 02 - Data Cleaning

## Objetivo

Generar datasets intermedios listos para ingeniería de características (feature engineering).

## Entrada
- `data/raw/contract.csv`
- `data/raw/personal.csv`
- `data/raw/internet.csv`
- `data/raw/phone.csv`

## Salida
- `data/interim/contract_clean.csv`
- `data/interim/personal_clean.csv`
- `data/interim/internet_clean.csv`
- `data/interim/phone_clean.csv`

In [51]:
## Inicialización
import pandas as pd

In [52]:
## Cargar datos
raw_path = '../data/raw/' # Directorio para datos raw
df_contract = pd.read_csv(raw_path+'contract_raw.csv')
df_personal = pd.read_csv(raw_path+'personal_raw.csv')
df_internet = pd.read_csv(raw_path+'internet_raw.csv')
df_phone = pd.read_csv(raw_path+'phone_raw.csv')

### Archivo 1 (contract.csv)

In [53]:
# Convertir tipo de dato a las columnas de fechas 
df_contract = pd.read_csv(raw_path+'contract.csv', parse_dates=['BeginDate','EndDate'])

C:\Users\RCorrea\AppData\Local\Temp\ipykernel_19492\496871927.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_contract = pd.read_csv(raw_path+'contract.csv', parse_dates=['BeginDate','EndDate'])

In [54]:
df_contract.isna().sum()

customerID          0
BeginDate           0
EndDate             0
Type                0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [55]:
# Validar cambio de tipo
df_contract.dtypes

customerID                  object
BeginDate           datetime64[ns]
EndDate                     object
Type                        object
PaperlessBilling            object
PaymentMethod               object
MonthlyCharges             float64
TotalCharges                object
dtype: object

In [56]:
# Estandarizar nombres de columnas
df_contract.rename(columns={'customerID': 'customer_id', 'BeginDate':'begin_date', 'EndDate':'end_date', 
                            'Type':'type', 'PaperlessBilling':'paperless_billing', 'PaymentMethod':'payment_method',
                            'MonthlyCharges':'monthly_charges', 'TotalCharges':'total_charges'}, inplace=True)

In [57]:
# Inspección de algunos elementos para tener mayor familaridad
df_contract.head()

,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges
0,7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,2016-05-01,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,2019-09-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,70.70,151.65

In [58]:
# Buscar duplicados totales
df_contract.duplicated().sum()

0

No hay duplicados. A continuación se investiga si hay valores incongruentes en alguna característica.

In [59]:
# customer_id - al ser id no debería tener duplicados
df_contract['customer_id'].duplicated().sum()

0

In [60]:
# begin_date
print("periodo del ",df_contract['begin_date'].min(), "al ",df_contract['begin_date'].max())

periodo del  2013-10-01 00:00:00 al  2020-02-01 00:00:00

In [61]:
# begin_date
df_contract['begin_date'].value_counts()

begin_date
2014-02-01    366
2019-10-01    237
2019-11-01    237
2019-09-01    237
2020-01-01    233
             ...
2020-02-01     11
2014-01-01      7
2013-10-01      3
2013-12-01      3
2013-11-01      2
Name: count, Length: 77, dtype: int64

In [62]:
# end_date
df_contract['end_date'].value_counts()

end_date
No                     5174
2019-11-01 00:00:00     485
2019-12-01 00:00:00     466
2020-01-01 00:00:00     460
2019-10-01 00:00:00     458
Name: count, dtype: int64

De los cinco distintos valores cuatro son fechas, al inicio de algunos meses, y existe el valor 'No'. La proporción de contratos terminados es, gruesamente, del 25%

In [63]:
# type
df_contract['type'].value_counts()

type
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [64]:
# paperless_billing
df_contract['paperless_billing'].value_counts()

paperless_billing
Yes    4171
No     2872
Name: count, dtype: int64

In [65]:
# payment_method
df_contract['payment_method'].value_counts()

payment_method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [66]:
# monthly_charges
df_contract['monthly_charges'].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: monthly_charges, dtype: float64

In [67]:
# total_charges
df_contract['total_charges'].sort_values().unique()

array([' ', '100.2', '100.25', ..., '999.45', '999.8', '999.9'],
      dtype=object)

In [68]:
# investigar cómo se ven los datos cuando total_charges = ' '
df_contract[df_contract['total_charges']==' '].head(10)

,customer_id,begin_date,end_date,type,paperless_billing,payment_method,monthly_charges,total_charges
488,4472-LVYGI,2020-02-01,No,Two year,Yes,Bank transfer (automatic),52.55,
753,3115-CZMZD,2020-02-01,No,Two year,No,Mailed check,20.25,
936,5709-LVOEQ,2020-02-01,No,Two year,No,Mailed check,80.85,
1082,4367-NUYAO,2020-02-01,No,Two year,No,Mailed check,25.75,
1340,1371-DWPAZ,2020-02-01,No,Two year,No,Credit card (automatic),56.05,
3331,7644-OMVMY,2020-02-01,No,Two year,No,Mailed check,19.85,
3826,3213-VVOLG,2020-02-01,No,Two year,No,Mailed check,25.35,
4380,2520-SGTTA,2020-02-01,No,Two year,No,Mailed check,20.00,
5218,2923-ARZLG,2020-02-01,No,One year,Yes,Mailed check,19.70,
6670,4075-WKNIU,2020-02-01,No,Two year,No,Mailed check,73.35,

Se observa que todos los datos corresponden a contratos que inician al final del horizonte de tiempo, es decir contrantos nuevos y por tanto no han recibido cargos. Entonces se pueden reemplazar  (' ' $\rightarrow$ 0)

In [69]:
# Validar observación
df_contract.loc[df_contract['total_charges']==' ','begin_date'].unique()

<DatetimeArray>
['2020-02-01 00:00:00']
Length: 1, dtype: datetime64[ns]

In [70]:
# Se reemplazar cadenas en blanco por cero
df_contract['total_charges'] = df_contract['total_charges'].replace(' ', 0)

In [71]:
# Cambiar el tipo de dato
df_contract['total_charges'] = df_contract['total_charges'].astype("float")

In [72]:
df_contract.dtypes

customer_id                  object
begin_date           datetime64[ns]
end_date                     object
type                         object
paperless_billing            object
payment_method               object
monthly_charges             float64
total_charges               float64
dtype: object

### Segundo archivo (personal.csv)

In [73]:
# Resumen inicial
df_personal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [74]:
# Estandarizar nombres de columnas
df_personal.rename(columns={'customerID': 'customer_id', 'SeniorCitizen':'senior_citizen',
                            'Partner':'partner', 'Dependents':'dependents'}, inplace=True)

In [75]:
# Inspección de algunos elementos para tener mayor familaridad
df_personal.head()

  customer_id  gender  senior_citizen partner dependents
0  7590-VHVEG  Female               0     Yes         No
1  5575-GNVDE    Male               0      No         No
2  3668-QPYBK    Male               0      No         No
3  7795-CFOCW    Male               0      No         No
4  9237-HQITU  Female               0      No         No

In [76]:
# Buscar duplicados totales
df_personal.duplicated().sum()

0

In [77]:
# Analizar valores de cada columna, ya sabemos que no hay valores ausentes None
# customer_id - al ser id no debería tener duplicados
df_personal['customer_id'].duplicated().sum()

0

In [78]:
# gender
df_personal['gender'].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [79]:
# senior_citizen

# Reemplazar números por Yes/No para seguir el mismo patrón que el resto de variables binarias
df_personal['senior_citizen'] = df_personal['senior_citizen'].apply(lambda x: 'Yes' if x ==1 else 'No')
df_personal['senior_citizen'].value_counts()

senior_citizen
No     5901
Yes    1142
Name: count, dtype: int64

In [80]:
# partner
df_personal['partner'].value_counts()

partner
No     3641
Yes    3402
Name: count, dtype: int64

In [81]:
# dependents
df_personal['dependents'].value_counts()

dependents
No     4933
Yes    2110
Name: count, dtype: int64

### Tercer archivo (internet.csv)

In [82]:
# Resumen inicial
df_internet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5517 non-null   object
 1   InternetService   5517 non-null   object
 2   OnlineSecurity    5517 non-null   object
 3   OnlineBackup      5517 non-null   object
 4   DeviceProtection  5517 non-null   object
 5   TechSupport       5517 non-null   object
 6   StreamingTV       5517 non-null   object
 7   StreamingMovies   5517 non-null   object
dtypes: object(8)
memory usage: 344.9+ KB

In [83]:
df_internet.rename(columns={'customerID': 'customer_id', 'InternetService':'internet_service',
                            'OnlineSecurity':'online_security', 'OnlineBackup':'online_backup',
                            'DeviceProtection':'device_protection', 'TechSupport':'tech_support',
                            'StreamingTV':'streaming_tv', 'StreamingMovies':'streaming_movies'}, inplace=True)

In [84]:
# Inspección de algunos elementos para tener mayor familaridad
df_internet.head()

,customer_id,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies
0,7590-VHVEG,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Fiber optic,No,No,No,No,No,No

In [85]:
# Buscar duplicados totales
df_internet.duplicated().sum()

0

**Analizar valores de cada columna, ya sabemos que no hay valores ausentes None**

In [86]:
# customer_id - al ser id no debería tener duplicados
df_internet['customer_id'].duplicated().sum()

0

In [87]:
# internet_service
df_internet['internet_service'].value_counts()

internet_service
Fiber optic    3096
DSL            2421
Name: count, dtype: int64

In [88]:
# online_security
df_internet['online_security'].value_counts()

online_security
No     3498
Yes    2019
Name: count, dtype: int64

In [89]:
# online_backup
df_internet['online_backup'].value_counts()

online_backup
No     3088
Yes    2429
Name: count, dtype: int64

In [90]:
# device_protection
df_internet['device_protection'].value_counts()

device_protection
No     3095
Yes    2422
Name: count, dtype: int64

In [91]:
# tech_support
df_internet['tech_support'].value_counts()

tech_support
No     3473
Yes    2044
Name: count, dtype: int64

In [92]:
# streaming_tv
df_internet['streaming_tv'].value_counts()

streaming_tv
No     2810
Yes    2707
Name: count, dtype: int64

In [93]:
# streaming_movies
df_internet['streaming_movies'].value_counts()

streaming_movies
No     2785
Yes    2732
Name: count, dtype: int64

El hecho de que este archivo tiene 5517 registros, 1526 menos que los archivos anteriores indica (con más razón al observar los valores de 'internet_service') que esta diferencia corresponde a clientes que **no contrataron** servicio de intenet.

### Cuarto archivo (phone.csv)

In [94]:
# Resumen inicial
df_phone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6361 entries, 0 to 6360
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     6361 non-null   object
 1   MultipleLines  6361 non-null   object
dtypes: object(2)
memory usage: 99.5+ KB

In [95]:
df_phone.rename(columns={'customerID': 'customer_id', 'MultipleLines':'multiple_lines'}, inplace=True)

In [96]:
# Inspección de algunos elementos para tener mayor familaridad
df_phone.head()

  customer_id multiple_lines
0  5575-GNVDE             No
1  3668-QPYBK             No
2  9237-HQITU             No
3  9305-CDSKC            Yes
4  1452-KIOVK            Yes

In [97]:
# Buscar duplicados totales
df_phone.duplicated().sum()

0


Analizar valores de cada columna, ya sabemos que no hay valores ausentes None

In [98]:
# customer_id - al ser id no debería tener duplicados
df_phone['customer_id'].duplicated().sum()

0

In [99]:
# multiple_lines
df_phone['multiple_lines'].value_counts()

multiple_lines
No     3390
Yes    2971
Name: count, dtype: int64

Este archivo tiene 6361 registros, 682 menos que df_personal.csv Esto se interpreta como clientes **sin línea telefónica**.

### Exportar datos

In [100]:
interim_path = '../data/interim/' # Directorio para datos limpios
df_contract.to_csv(interim_path+'contract_clean.csv', index=False)
df_personal.to_csv(interim_path+'personal_clean.csv', index=False)
df_internet.to_csv(interim_path+'internet_clean.csv', index=False)
df_phone.to_csv(interim_path+'phone_clean.csv', index=False)